# Generated by Django 4.1.3 on 2023-02-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EducationsLiences', models.TextField(max_length=100)),
                ('DocImage', models.ImageField(upload_to='images')),
            ],
        ),
    ]
