# Generated by Django 4.1.3 on 2023-02-22 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctorinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EducationsLiences', models.TextField(max_length=100)),
                ('DocImage', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorsAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfAppoiment', models.DateField(blank=True, null=True)),
                ('LocationOfAppoiment', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('begin_time', models.DateTimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('Online', models.BooleanField()),
                ('DoctorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='BookedAppoiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Khartoum', 'Khartoum'), ('Bahri', 'Bahri'), ('Omdorman', 'Omdorman')], max_length=12)),
                ('Date', models.DateField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('PatientName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='doctor.patient')),
                ('doctorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='doctor.doctor')),
            ],
        ),
    ]
