# Generated by Django 4.1.3 on 2023-02-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_patientinfo_doctorsappointment_bookedappoiments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('VaccID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Age', models.IntegerField(max_length=10)),
                ('WhatBefor', models.CharField(max_length=255)),
                ('WhatAfter', models.CharField(max_length=255)),
                ('WhatToDo', models.CharField(max_length=255)),
                ('Symptoms', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('Khartoum', 'Khartoum'), ('Bahri', 'Bahri'), ('Omdorman', 'Omdorman')], max_length=12)),
            ],
        ),
    ]
