# Generated by Django 4.1.3 on 2023-02-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_vaccine'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bahri', models.CharField(max_length=100000)),
                ('Khartoum', models.CharField(max_length=100000)),
                ('OmDurman', models.CharField(max_length=100000)),
            ],
        ),
    ]
