# Generated by Django 4.1.3 on 2023-02-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_remove_patient_id_alter_patient_idnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='idNum',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
