# Generated by Django 4.1.3 on 2023-02-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_remove_doctor_id_alter_doctor_idnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
